spring:
  application:
    name: authzen
  datasource:
    url: jdbc:mysql://localhost:3306/authzen?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  security:
    user:
      name: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: youremail@gmail.com
    password: yourapppassword
    protocol: smtp
    tls: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  web:
    resources:
      static-locations: classpath:/static/

jwt:
  secret: 5pXqZ6eY7kR2mL9vW3uT4yN8xQ0zA1B2C
  access-token:
    expiry-ms: 900000
  refresh-token:
    expiry-ms: 604800000

server:
  port: 8080

email:
  from: noreply@yourdomain.com

github:
  client-id: Ov23li4hZXTmiFgAzkkP
  client-secret: 100fd942458068fbde161ded16c0c8804f37ecc1
  redirect-uri: http://localhost:8080/oauth/callback

admin:
  email: admin@yourdomain.com
  username: admin
  password: Admin@123

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    display-request-duration: true